---
driver:
  name: digitalocean
  customize:
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mule-test::default]
    attributes:
      aws:
        access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
